
name: CI

# Controls when the action will run. Triggers the workflow on repository dispatch
# events but only for the master branch
on: 
  push:
    branches: master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your  repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Create Event Subscription
      id: azure_eventgridsubscriber
      uses: mlopstemplates/azure_eventgridsubscriber@master
      with:
        azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
        events_to_subscribe: |
            Microsoft.Storage.BlobCreated
            Microsoft.Storage.BlobDeleted
            Microsoft.Storage.BlobRenamed	
            Microsoft.Storage.DirectoryCreated	
            Microsoft.Storage.DirectoryRenamed	
            Microsoft.Storage.DirectoryDeleted	
        provider_type: "Microsoft.Storage/storageAccounts/mydlsg"
        resource_group: "azure-sample"
        pattoken: ${{secrets.PATTOKEN}}
