name: CI

# Controls when the action will run. Triggers the workflow on repository dispatch
# events but only for the master branch
on: 
  repository_dispatch:
    types: [storage-blobcreated, storage-blobdeleted, storage-blobrenamed, storage-directorycreated, storage-directoryrenamed, storage-directorydeleted]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your  repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Check variables
      env:
        PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
      run: |
          echo  "${{ toJson(github.event.client_payload.data) }}"
          echo  "${{ toJson(github.event.client_payload.eventType) }}"
          echo  "${{ toJson(github.event.client_payload.data.contentType) }}"
          echo  "${{ github.event.client_payload.data.contentType }}"
